// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: assignRenderer/assignRenderer.proto

package assignRenderer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssignorClient is the client API for Assignor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssignorClient interface {
	Request(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerInfo, error)
}

type assignorClient struct {
	cc grpc.ClientConnInterface
}

func NewAssignorClient(cc grpc.ClientConnInterface) AssignorClient {
	return &assignorClient{cc}
}

func (c *assignorClient) Request(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, "/assignRenderer.Assignor/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssignorServer is the server API for Assignor service.
// All implementations must embed UnimplementedAssignorServer
// for forward compatibility
type AssignorServer interface {
	Request(context.Context, *ClientRequest) (*ServerInfo, error)
	mustEmbedUnimplementedAssignorServer()
}

// UnimplementedAssignorServer must be embedded to have forward compatible implementations.
type UnimplementedAssignorServer struct {
}

func (UnimplementedAssignorServer) Request(context.Context, *ClientRequest) (*ServerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedAssignorServer) mustEmbedUnimplementedAssignorServer() {}

// UnsafeAssignorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssignorServer will
// result in compilation errors.
type UnsafeAssignorServer interface {
	mustEmbedUnimplementedAssignorServer()
}

func RegisterAssignorServer(s grpc.ServiceRegistrar, srv AssignorServer) {
	s.RegisterService(&Assignor_ServiceDesc, srv)
}

func _Assignor_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignorServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assignRenderer.Assignor/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignorServer).Request(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Assignor_ServiceDesc is the grpc.ServiceDesc for Assignor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Assignor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assignRenderer.Assignor",
	HandlerType: (*AssignorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _Assignor_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assignRenderer/assignRenderer.proto",
}
